type: federated
total_rounds: 500
batch_size: 16
use_sample_weights: True
client_optimizer:
  _target_: tensorflow.keras.optimizers.SGD
  learning_rate: 0.01
server_optimizer:
  _target_: tensorflow.keras.optimizers.SGD
  learning_rate: 1.0
  momentum: 0.0
n_total_clients: 5
n_clients_per_round:
client_sampling_prob: 0.5
split_clients_by: dzclass
drop_split_columns: False
local_epochs: 1
personalisation: False
single_client_validation: False